### PR TITLE
Controller update fixes

### PR DESCRIPTION
**Pull request by jabdoa2**
As promised in [# ](https://github.com/wave-k8s/wave/pull/145) a PR to fix the controller and all the tests.

This should be fine this way. In some places I had to run the controller twice in tests which looks odd to me. I did not look further into it but it might be worth investigating.

### CODE REVIEW

**Comment by jabdoa2** [comment]
Tests seem to fail since they use an ancient go version. Will update that later

**Comment by jabdoa2** [comment]
Verified that github actions pass locally. Should be good to go.

**Comment by jabdoa2** [comment]
Ok some more cleanup. Also reenabled the linter in the recommended way and fixed all the lints.

**Comment by Dentrax** [comment]
Thank you so much for your work here! @jabdoa2 🚀 Really appreciated.

**Pull request merged**
